version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: cicd_worker_local
    env_file: .env # Reads REDIS_URL and DATABASE_URL from .env file
    volumes:
      # Mounts your local machine's Docker daemon so the worker can spawn pipelines
      - /var/run/docker.sock:/var/run/docker.sock
# Note: You only need to run THIS file locally using: 
# docker-compose -f docker-compose.worker.yml up --build
